# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x08tutorial\"s\n\x04User\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\'\n\x04role\x18\x03 \x02(\x0e\x32\x13.tutorial.User.Role:\x04USER\"(\n\x04Role\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x0b\n\x07MANAGER\x10\x01\x12\x08\n\x04USER\x10\x02\"1\n\x11PermissionRequest\x12\x1c\n\x04user\x18\x01 \x02(\x0b\x32\x0e.tutorial.User\":\n\x0ePermissionBody\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0e\n\x06result\x18\x03 \x02(\x08\"@\n\x12PermissionResponse\x12*\n\x08response\x18\x01 \x02(\x0b\x32\x18.tutorial.PermissionBody\"\x1f\n\rStatusRequest\x12\x0e\n\x06status\x18\x01 \x02(\t\"@\n\x11SuccessStatusBoby\x12\x15\n\rtext_response\x18\x01 \x02(\t\x12\x14\n\x0cint_response\x18\x02 \x02(\x05\"?\n\x0eStatusResponse\x12-\n\x08response\x18\x01 \x02(\x0b\x32\x1b.tutorial.SuccessStatusBoby2[\n\nPermission\x12M\n\x0eSendPermission\x12\x1b.tutorial.PermissionRequest\x1a\x1c.tutorial.PermissionResponse\"\x00\x32K\n\x06Status\x12\x41\n\nSendStatus\x12\x17.tutorial.StatusRequest\x1a\x18.tutorial.StatusResponse\"\x00\x42\x32\n\x19io.grpc.examples.tutorialB\rTutorialProtoP\x01\xa2\x02\x03TUT')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031io.grpc.examples.tutorialB\rTutorialProtoP\001\242\002\003TUT'
  _USER._serialized_start=26
  _USER._serialized_end=141
  _USER_ROLE._serialized_start=101
  _USER_ROLE._serialized_end=141
  _PERMISSIONREQUEST._serialized_start=143
  _PERMISSIONREQUEST._serialized_end=192
  _PERMISSIONBODY._serialized_start=194
  _PERMISSIONBODY._serialized_end=252
  _PERMISSIONRESPONSE._serialized_start=254
  _PERMISSIONRESPONSE._serialized_end=318
  _STATUSREQUEST._serialized_start=320
  _STATUSREQUEST._serialized_end=351
  _SUCCESSSTATUSBOBY._serialized_start=353
  _SUCCESSSTATUSBOBY._serialized_end=417
  _STATUSRESPONSE._serialized_start=419
  _STATUSRESPONSE._serialized_end=482
  _PERMISSION._serialized_start=484
  _PERMISSION._serialized_end=575
  _STATUS._serialized_start=577
  _STATUS._serialized_end=652
# @@protoc_insertion_point(module_scope)
