version: "3.9"


services:
  permission_service:
    build:
      context: ./permission_service
      dockerfile: Dockerfile
    container_name: "permission_service"
    ports:
      - "50051:50051"
    volumes:
      - .:/src/app/
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: "client"
    volumes:
      - .:/src/app/
    depends_on:
      - permission_service


